[Multiple] Sheet Additions/Field additions
ufx/SaintCoinach pull request #216
Opened 2019-04-05 15:36 UTC by Khyrou

2019-04-06 07:20 UTC, goaaats requested changes

2019-04-06 07:20 UTC, goaaats commented on SaintCoinach/SaintCoinach.csproj
> -    <Compile Include="Xiv\ItemActions\CustomizeUnlock.cs" />
Why'd you remove CustomizeUnlock?

2019-04-06 07:20 UTC, goaaats commented on SaintCoinach/Xiv/XivRow.cs
> +        public int[] convertToIntArray(string column) {
You should fix the naming style on this one

2019-04-20 18:11 UTC, IcarusTwine commented on SaintCoinach/ex.json
> -          }
Is this an Error or something i've missed?

2019-04-20 22:14 UTC, closed without merging